apiVersion: v1
kind: Service
metadata:
  name: kubot-service
spec:
  selector:
    app: kubot-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubot-app
spec:
  selector:
    matchLabels:
      app: kubot-app
  replicas: 3
  template:
    metadata:
      labels:
        app: kubot-app
    spec:
      containers:
      - name: kubot-app
        image: kubot-discord-bot
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000